### ISSUE TITLE
Run parameters file

### ISSUE THREAD

**Issue by wing2250** [FischbachLab/nf-miseq-16s-dada2#1]
Context: Currently, the run parameters (e.g. truncLen, overlap, minBoot, and so on) are not found in the results folder. However, the run parameters affect the results and thus interpret the results better.  

As the run parameter affects the results, it would be nice to automatically generate output files of the 'run parameters' and/or 'software versions' for each run.

**Comment by xmeng** [comment]
@wing2250 

Instead of saving the parameters in the output logs, a configuration file is required to input a list of run parameters as an option (-config file_name).
A copy of the customized configuration will be saved as Logs/parameters.yaml in the project output folder.

**Comment by xmeng** [comment]
Fix for Issues #1
